import { FormEvent, useState } from "react";
import classes from "./UploadForm.module.scss";
import { Button, Form, FormControl, FormGroup } from "react-bootstrap";
import { backendUrl } from "../store/backend-url";
import { useNavigate } from "react-router";
import { useUpdateImageItems } from "../hooks/useUpdateImageItems";
import { useFormField } from "../hooks/useFormField";

type UploadFormProps = {
  title?: string;
  description?: string;
  initialUpload?: boolean;
}

function UploadForm(props: Readonly<UploadFormProps>) {
  const [submitting, setSubmitting] = useState(false);
  const navigate = useNavigate();
  const updateImagesState = useUpdateImageItems();

  const submitHandler = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    // Note: this is just in case the user manually changes the button's disabled tag to false
    if (
      !titleValid ||
      !descriptionValid ||
      !imageValid
    ) {
      setTouchedEvents.forEach(setTouched => setTouched(true));
      return;
    }

    setSubmitting(true);

    const formData = new FormData();

    formData.append("image", image!);
    formData.append("title", title);
    formData.append("description", description);

    await fetch(`${backendUrl}/form`, {
      method: "POST",
      body: formData,
    });

    // Note: because the ID is generated by the database, we need to reload the items
    updateImagesState();
    navigate("/");
  };

  function makeInitialState<T>(value: T): {
    touched: boolean;
    isValid: boolean;
    value: T;
    errorMessage: string | undefined;
  } {
    return {
      touched: false,
      isValid: false,
      value,
      errorMessage: undefined,
    }
  }

  const [titleComponent, titleValid, title, setTitleTouched] = useFormField(
    FormControl,
    { as: "input" },
    makeInitialState(props.title ?? ""),
    (event) => event.target.value,
    (value) => {
      if (value.length === 0) {
        return "Title is required"
      }
    }
  );

  const [
    descriptionComponent,
    descriptionValid,
    description,
    setDescriptionTouched,
  ] = useFormField(
    FormControl,
    { as: "textarea", style: { height: "300px" } },
    makeInitialState(props.description ?? ""),
    (event) => event.target.value,
    (value) => {
      if (value.length === 0) {
        return "Description is required"
      }
    }
  );

  const [imageComponent, imageValid, image, setImageTouched] = useFormField(
    FormControl,
    { type: "file", accept: "image/*" },
    makeInitialState(null),
    (event) => event.target.files![0],
    (value) => {
      if (!value && !props.initialUpload) {
        return "Image is required"
      }
    }
  );

  const setTouchedEvents = [
    setTitleTouched,
    setDescriptionTouched,
    setImageTouched,
  ]

  return (
    <div className={classes["upload-form"]}>
      <Form onSubmit={submitHandler}>
        <FormGroup>
          <Form.Label>Title</Form.Label>
          {titleComponent}
        </FormGroup>

        <FormGroup>
          <Form.Label>Image</Form.Label>
          {imageComponent}
        </FormGroup>

        <FormGroup>
          <Form.Label>Description</Form.Label>
          {descriptionComponent}
        </FormGroup>

        <Button
          disabled={
            !titleValid ||
            !descriptionValid ||
            !imageValid ||
            submitting
          }
          className={classes.submit}
          type="submit"
        >
          Submit
        </Button>
      </Form>
    </div>
  )
}

export default UploadForm;