import { useNavigate } from "react-router";
import UploadForm, { UploadFormSubmitEvent } from "../Components/UploadForm";
import { backendUrl } from "../store/backend-url";
import { useUpdateImageItems } from "../hooks/useUpdateImageItems";

function UploadPage() {
  const navigate = useNavigate();
  const updateImagesState = useUpdateImageItems();

  const submitHandler: UploadFormSubmitEvent = async (title, description, image) => {
    const formData = new FormData();

    formData.append("image", image!);
    formData.append("title", title);
    formData.append("description", description);

    await fetch(`${backendUrl}/form`, {
      method: "POST",
      body: formData,
    });

    // Note: because the ID is generated by the database, we need to reload the items
    updateImagesState();
    navigate("/");
  }

  return <UploadForm updating={false} onSubmit={submitHandler} />
}

export default UploadPage;