import { useNavigate } from "react-router";
import { backendUrl } from "../store/backend-url";
import { useUpdateImageItems } from "../hooks/useUpdateImageItems";
import { useUploadForm } from "../hooks/useUploadForm";
import { Category } from "../store/images-store";

function UploadPage() {
  const navigate = useNavigate();
  const updateImagesState = useUpdateImageItems();

  async function submitHandler (title: string, description: string, image: File | null, category: Category) {
    const formData = new FormData();

    formData.append("image", image!);
    formData.append("title", title);
    formData.append("description", description);
    formData.append("category", category);

    const response = await fetch(`${backendUrl}/form`, {
      method: "POST",
      body: formData,
    });

    if (response.status > 299) {
      errorHandler();
      return;
    }

    // Note: because the ID is generated by the database, we need to reload the items
    updateImagesState();
    navigate("/");
  }

  const [uploadForm, errorHandler] = useUploadForm({
    updating: false,
    onSubmit: submitHandler,
  });

  // return <UploadForm updating={false} onSubmit={submitHandler} />
  return uploadForm;
}

export default UploadPage;